#!/bin/bash

PATH_TO_COURSE=$HOME/Documents/cours3/
COURS=('algo' 'lanc' 'pweb' 'anglais')

matiere=4
while [ $matiere -lt 0 ] || [ $matiere -gt 3 ]; do
    for i in ${!COURS[*]}; do
        echo -e "[$i] ${COURS[$i]}"
    done
    read -p "Choisissez la matiere en cours: " matiere
done

if [ -L ~/Cours ]; then
    rm ~/Cours
    echo "Old link removed."
fi

if [ -e ~/Cours ]; then
    echo "~/Cours already exists."
else
    PATH_TO_COURSE="$PATH_TO_COURSE""${COURS[$matiere]}"
    ln -s $PATH_TO_COURSE ~/Cours
    echo "Link created to $PATH_TO_COURSE"
fi
