require("evil.volume")
require("evil.battery")
require("evil.cpu")
require("evil.temperature")
require("evil.ram")
require("evil.weather")
require("evil.mpd")
require("evil.brightness")
require("evil.disk")(9)
require("evil.disk")(10)
require("evil.disk")(12)
require("evil.dynamic-wallpaper")
-- -- require("evil.spotify")
