-- An applications menu
-- Required depends: awesome-freedesktop or xdg_menu
-- awesome-freedesktop : automatic
-- xdg_menu : manual
-- Your choice

local awful = require("awful")
local gears = require("gears")
local beautiful = require("beautiful")
local apps = require('configuration.apps')

local hotkeys_popup = require('awful.hotkeys_popup').widget

terminal = apps.default.terminal
web_browser = apps.default.web_browser
file_manager = apps.default.file_manager
text_editor = apps.default.text_editor
editor_cmd = "vim" 


-- icon theme is in `awesome/theme/default-theme.lua`
-- Search for `theme.icon_theme`

-- Check first if freedesktop module is installed
-- `awesome-freedesktop-git` is in AUR
-- https://github.com/lcpz/awesome-freedesktop
-- Check on your distro's repo

-- Checks if module exists, it will also checks syntax. 
-- Will return false if syntax error in module
local function is_module_available(name)
	if package.loaded[name] then
		return true
	else
		for _, searcher in ipairs(package.searchers or package.loaders) do
			local loader = searcher(name)
			if type(loader) == 'function' then
				package.preload[name] = loader
				return true
			end
		end
		return false
	end
end

-- Create a launcher widget and a main menu
myawesomemenu = {
	{ "Hotkeys", function() hotkeys_popup.show_help(nil, awful.screen.focused()) end },
	{ "Edit config", editor_cmd .. " " .. awesome.conffile },
	{ "Restart", awesome.restart },
	{ "Quit", function() awesome.quit() end },
}


-- Screenshot menu
local screenshot = {
	{"Full", function() 
		awful.spawn.easy_async_with_shell(apps.bins.full_screenshot, 
			function() 
			end
		)
	end},
	{"Area", function() 
		awful.spawn.easy_async_with_shell(apps.bins.area_screenshot, 
			function() 
			end
		)
	end}
}


-- Generate a list of app
if is_module_available("freedesktop") == true then

	-- A menu generated by awesome-freedesktop
	-- https://github.com/lcpz/awesome-freedesktop

	local freedesktop = require("freedesktop")
	local menubar = require("menubar")

	mymainmenu = freedesktop.menu.build({
		-- Not actually the size, but the quality of the icon
		icon_size = 48,

		before = {
			{ "Terminal", terminal, menubar.utils.lookup_icon("utilities-terminal") },
			{ "Web browser", web_browser, menubar.utils.lookup_icon("webbrowser-app") },
			{ "File Manager", file_manager, menubar.utils.lookup_icon("system-file-manager") },
			{ "Text Editor", text_editor, menubar.utils.lookup_icon("accessories-text-editor") },
			-- other triads can be put here
		},
		after = {
			{"Awesome", myawesomemenu, beautiful.awesome_icon},
			{"Take a Screenshot", screenshot, menubar.utils.lookup_icon("accessories-screenshot") },
			{"End Session", function() _G.exit_screen_show() end, menubar.utils.lookup_icon("system-shutdown") },
			-- other triads can be put here
		}

	})
	mylauncher = awful.widget.launcher({ image = beautiful.awesome_icon, menu = mymainmenu })


else
	--local instruction = {
		--{"Show instruction", function() 
			--require('naughty').notification({
				--title = 'Generate a list of menu',
				--message = "xdg_menu --format awesome --root-menu /etc/xdg/menus/arch-applications.menu MENU.lua",
				--app_name = 'System Notification',
				--timeout = 0,
				--urgency = 'critical'
			--})
		--end}
	--}


	mymainmenu = awful.menu({
		items = {
			{ "Terminal", terminal },
			{ "Web browser", web_browser },
			{ "File Manager", file_manager },
			{ "Text Editor", text_editor },
			{"Awesome", myawesomemenu},
			{"Take a Screenshot", screenshot }
		}
	})

	mylauncher = awful.widget.launcher({ image = beautiful.awesome_icon, menu = mymainmenu })

end

-- Embed mouse bindings
root.buttons(
	gears.table.join(
		awful.button(
			{}, 
			3, 
			function () 
				mymainmenu:toggle() 
			end
		),
		awful.button(
			{}, 
			1,
		 	function()
				mymainmenu:hide()
		 	end
		)
	)
)
