#! /bin/sh

sxhkd &
nm-applet &
#python3 ~/work/perso/Python/clip_daemon/daemon.py&
#feh --bg-scale ~/Images/Background/circuit.jpg
#feh --bg-scale /usr/share/backgrounds/gnome/adwaita-day.jpg
#feh --bg-scale ~/Pictures/Wallpapers/katana.png
feh --bg-scale ~/Pictures/Wallpapers/red_snake.jpg
$XDG_CONFIG_HOME/polybar/launch.sh &
#killall -q picom
#picom &
killall -q conky
conky &

xrandr --output DP2 --right-of eDP1 --auto
xrandr --output DP1 --left-of eDP1 --auto

bspc monitor eDP1 -d 1 2 3 4 5 6
bspc monitor DP1 -d 7 8
bspc monitor DP2 -d 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a termite desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a firefoxdeveloperedition desktop='^2'
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
